name: Create or Destroy queue

on:
  workflow_dispatch:
    inputs:
      queueName:
        description: Queue name to create
        required: true
      action:
        type: choice
        description: Action
        options:
        - Create
        - Destroy

jobs:
   
  setup: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Add profile credentials to ~/.aws/credentials
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Execute terraform script to create queue
        if: github.event.inputs.action == 'Create'
        run: |
          cd infra/sqs
          terraform init
          terraform apply -auto-approve -var="queue_name=${{ github.event.inputs.queueName }}"

      - name: Execute terraform script to destroy queue
        if: github.event.inputs.action == 'Destroy'
        run: |
          cd infra/sqs
          terraform init
          terraform destroy -auto-approve -var="queue_name=${{ github.event.inputs.queueName }}"


